name: pedidos
description: 'A new Flutter project. Created by Slidy'

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2+2
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+3
  shared_preferences_web: ^0.1.2+4
  font_awesome_flutter: ^8.7.0
  google_fonts: ^0.3.10
  animate_do: ^1.6.3
  flushbar: ^1.10.0
  moor_flutter: ^2.1.1
  http: ^0.12.0+4
  progress_dialog: ^1.2.2
  expansion_tile_card: ^1.0.3
  #call_number: 
  maps_launcher: ^1.2.0
  url_launcher_web: ^0.1.1+6
  location: ^3.0.2
  location_web: ^1.0.0
  flutter_phone_direct_caller: ^1.0.1
  jiffy: ^3.0.1
  flutter_touch_spin: ^1.0.1
  back_button_interceptor: ^4.3.0
  money2: ^1.4.3
  flutter_slidable: ^0.5.7

dev_dependencies:
  moor_generator: null
  mobx_codegen: null
  build_runner: null
  flutter_test:
    sdk: flutter

scripts:
  mobx: flutter pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/

